//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication14
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string email { get; set; }
        public string passwords { get; set; }
        public string batteryinfo { get; set; }
        public string codebar { get; set; }
        public Nullable<System.DateTime> timelogin { get; set; }
        public Nullable<System.DateTime> timelogout { get; set; }
    }
}
